baseURL = "/"
languageCode = "ru-ru"
title = "Заводится"

[params]
  title = 'Remix, a theme for Hugo fully editable with Netlify CMS'
  metaDescription = "Hugo + Netlify CMS + One click deploy to Netlify"

[taxonomies]
  category= "theme"
  scene = "scenes"
